"""empty message

Revision ID: dc59489a52ce
Revises: f1b3ffc59142
Create Date: 2017-11-26 05:31:51.755764

"""

# revision identifiers, used by Alembic.
revision = 'dc59489a52ce'
down_revision = 'f1b3ffc59142'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('champion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'player', ['champion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'champion_id')
    # ### end Alembic commands ###
