"""empty message

Revision ID: f1b3ffc59142
Revises: 0a34e051a918
Create Date: 2017-11-26 05:26:12.137749

"""

# revision identifiers, used by Alembic.
revision = 'f1b3ffc59142'
down_revision = '0a34e051a918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
